[package]
name = "chat-proto"
version = "0.1.0"
authors = ["Tsukasa Arima <pyar6329@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.4.3"
tonic-reflection = "0.1.0"
prost = "0.7.0"
prost-types = "0.7"

[build-dependencies]
tonic-build = "0.4.2"
