---
name: JavaScript Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run: 
        working-directory: javascript
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set GitHub Access Token for Other Repository
      env:
        ACCESS_TOKEN_FOR_GITHUB: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}
      run: |
        git config --global credential.helper store
        echo "https://${ACCESS_TOKEN_FOR_GITHUB}:@github.com" > ~/.git-credentials

    - name: Cache npm
      id: cache-npm
      uses: actions/cache@v2
      env:
        CACHE_VERSION: "0.1"
      with:
        path: |
          ~/.npm
          javascript/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('javascript/package-lock.json') }}-${{ env.CACHE_VERSION }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ hashFiles('javascript/package-lock.json') }}-
          ${{ runner.os }}-npm-

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install

    - name: Install protoc
      env:
        PROTOC_VERSION: "3.17.0"
      run: |
        curl -sL -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
        unzip protoc.zip
        chmod +x bin/protoc
        sudo mv bin/protoc /usr/local/bin/protoc
        mv include/* ../proto
        rm -rf protoc.zip readme.txt bin

    - name: Install protoc grpc-web
      env:
        PROTOC_GRPC_WEB_VERSION: "1.2.1"
      run: |
        curl -sL -o protoc-gen-grpc-web https://github.com/grpc/grpc-web/releases/download/${PROTOC_GRPC_WEB_VERSION}/protoc-gen-grpc-web-${PROTOC_GRPC_WEB_VERSION}-linux-x86_64
        chmod +x protoc-gen-grpc-web
        sudo mv protoc-gen-grpc-web /usr/local/bin/protoc-gen-grpc-web

    - name: Generate javascript files from proto
      run: make gen-proto

    - name: Run test
      run: npm test

  # release-tag:
  #   needs: test
  #   runs-on: ubuntu-20.04
  #   if: github.ref == 'refs/heads/main'
  #   outputs:
  #     tag: ${{ steps.release_tag.outputs.tag }}
  #   steps:
  #     - name: Get currentTime
  #       id: release_tag
  #       run: |
  #         TAG=$(date +"%Y%m%d.%H%M%S")
  #         echo ::set-output name=tag::${TAG}
  #
  # release:
  #   needs: release-tag
  #   runs-on: ubuntu-20.04
  #   if: github.ref == 'refs/heads/main'
  #   strategy:
  #     matrix:
  #       target: [x86_64-unknown-linux-musl]
  #   env:
  #     CACHE_VERSION: "0.0"
  #
  #   steps:
  #     - uses: actions/checkout@main
  #
  #     - name: Install dependencies
  #       if: matrix.target == 'x86_64-unknown-linux-musl'
  #       run: |
  #         sudo apt-get install -y musl-tools
  #
  #     - name: Set GitHub Access Token for Other Repository
  #       env:
  #         ACCESS_TOKEN_FOR_GITHUB: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}
  #       run: |
  #         git config --global credential.helper store
  #         echo "https://${ACCESS_TOKEN_FOR_GITHUB}:@github.com" > ~/.git-credentials
  #
  #     - name: Cache cargo
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/registry/index
  #           ~/.cargo/registry/cache
  #           ~/.cargo/git
  #           target
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ env.CACHE_VERSION }}-${{ matrix.target }}
  #         restore-keys: |
  #           ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ env.CACHE_VERSION }}
  #           ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-
  #           ${{ runner.os }}-cargo-
  #
  #     - name: Setup Rust
  #       uses: actions-rs/toolchain@v1
  #       if: matrix.target == 'x86_64-unknown-linux-musl'
  #       with:
  #         toolchain: stable
  #         profile: minimal
  #         target: ${{ matrix.target }}
  #
  #     - name: Build release binary for Linux
  #       uses: actions-rs/cargo@v1
  #       if: matrix.target == 'x86_64-unknown-linux-musl'
  #       with:
  #         use-cross: true
  #         command: build
  #         args: --release --target ${{ matrix.target }}
  #
  #     - name: Compress using Zstandard
  #       env:
  #         BINARY_PATH: target/${{ matrix.target }}/release
  #         TARGET: ${{ matrix.target }}
  #       run: |
  #         OS="Linux"
  #         echo ::set-output name=os::${OS}
  #         ARCH=${TARGET%%-*}
  #         echo ::set-output name=arch::${ARCH}
  #         mkdir dist
  #         tar -I "pzstd -19" -cvf "dist/grpc_chat-${OS}-${ARCH}.tar.zst" -C "$BINARY_PATH" grpc_chat
  #     
  #     - name: Hand over release binary to upload
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: dist
  #         path: ./dist
  #         retention-days: 1
  #
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       if: matrix.target == 'x86_64-unknown-linux-musl'
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}
  #
  #     - name: Build & Push Docker image
  #       uses: docker/build-push-action@v2
  #       if: matrix.target == 'x86_64-unknown-linux-musl'
  #       with:
  #         context: .
  #         file: .github/workflows/docker/Dockerfile
  #         push: true
  #         tags: |
  #           ghcr.io/${{ github.repository }}:${{ needs.release-tag.outputs.tag }}
  #           ghcr.io/${{ github.repository }}:latest
  #
  # upload:
  #   needs: [release-tag, release]
  #   runs-on: ubuntu-20.04
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #
  #     - name: Take over release binary from release-build
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: dist
  #
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ needs.release-tag.outputs.tag }}
  #         release_name: ${{ needs.release-tag.outputs.tag }}
  #         body: |
  #           ## Usage
  #           docker tag list: https://github.com/users/pyar6329/packages/container/package/chat-api
  #
  #           ```bash
  #           $ docker run -it -p "50051:50051" \
  #               -e "REDIS_HOSTNAME=localhost" \
  #               -e "REDIS_PASSWORD=foobar" \
  #               ghcr.io/pyar6329/chat-api:${{ needs.release-tag.outputs.tag }}
  #           ```
  #
  #           or get curl
  #
  #           ```bash
  #           $ curl -sLJO -H 'Accept: application/octet-stream' "https://$GITHUB_TOKEN@api.github.com/repos/pyar6329/chat-api/releases/assets/$( \
  #               curl -sL https://$GITHUB_TOKEN@api.github.com/repos/pyar6329/chat-api/releases/tags/${{ needs.release-tag.outputs.tag }} \
  #               | jq '.assets[] | select(.name | contains("Linux")) | .id')"
  #           ```
  #         draft: false
  #         prerelease: false
  #
  #     - name: Upload Release Asset
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_GITHUB }}
  #         TAG: ${{ needs.release-tag.outputs.tag }}
  #       run: |
  #         CPU_CORES=$(grep -c processor /proc/cpuinfo)
  #         find . -name "*.tar.zst" -type f -print | xargs -I {} -n 1 -P ${CPU_CORES} gh release upload ${TAG} {}
